# Generated by Django 6.0.6 on 2026-06-22 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0002_initial'),
        ('rentals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalagreement',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_borrower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_transactions', to='items.item'),
        ),
        migrations.AddField(
            model_name='rentaloffer',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_borrower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentaloffer',
            name='counter_offer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_offer', to='rentals.rentaloffer'),
        ),
        migrations.AddField(
            model_name='rentaloffer',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_transactions', to='items.item'),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='offer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreement', to='rentals.rentaloffer'),
        ),
    ]
